name = "CartesianOperators"
uuid = "6ffd2c7a-1a34-4f8b-a2c9-3d5e7f9b0c1d"
version = "0.1.0"

[deps]
CartesianGeometry = "5961ddb3-e46d-41f1-806c-0197ba873d0b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CartesianGeometry = "0.1"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
