[deps]
CartesianGeometry = "5961ddb3-e46d-41f1-806c-0197ba873d0b"
CartesianOperators = "6ffd2c7a-1a34-4f8b-a2c9-3d5e7f9b0c1d"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"

[sources]
CartesianOperators = {path = ".."}

[compat]
Documenter = "1"
